services:
    app:
        build: .
        
        env_file:
            - .env.local
            - .env
        ports:
            - '8000:8000'
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - .:/app
            - ./logs:/app/logs
        logging:
            driver: json-file
            options:
                tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
        networks:
            - mai_network
            - logging_network

        

    postgres:
        image: postgres:13-alpine
        env_file:
            - .env
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - mai_network
        

    redis:
        image: redis:6-alpine
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 5s
            retries: 5
        networks:
            - mai_network

    celery_worker:
        build: .
        env_file: .env
        command: celery -A app.api_v1.celery.service worker --loglevel=info --pool=solo
        depends_on:
            - redis
            - app
        volumes:
            - .:/app
        networks:
            - mai_network
    minio:
        image: minio/minio
        container_name: minio
        env_file:
            - .env
        ports:
            - "9001:9001"
        environment:
            MINIO_ACCESS_KEY: ${MINIO_ACCESS}
            MINIO_SECRET_KEY: ${MINIO_SECRET}
        volumes:
            - minio_data:/data
            - ./create_buckets.sh:/usr/bin/create_buckets.sh
        command: server /data --console-address :9001
        entrypoint: |
            sh -c "
                minio server --console-address \":9001\" /data &
                MINIO_PID=\$! &&
                sleep 5 &&
                /bin/sh /usr/bin/create_buckets.sh &&
                wait \$MINIO_PID
            "
        networks:
            - mai_network



volumes:
    minio_data:
    postgres_data:
    redis_data:

networks:
    mai_network:
        driver: bridge
