"""

Revision ID: 7cc86e5abcdb
Revises: 01ed532f8038
Create Date: 2025-05-29 19:07:08.392645

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cc86e5abcdb"
down_revision: Union[str, None] = "01ed532f8038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "nodes",
        "x",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
    )
    op.alter_column(
        "nodes",
        "y",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "nodes",
        "z",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.alter_column(
        "offices",
        "length",
        existing_type=sa.INTEGER(),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "offices",
        "width",
        existing_type=sa.INTEGER(),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    op.alter_column(
        "offices",
        "height",
        existing_type=sa.INTEGER(),
        type_=sa.FLOAT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "offices",
        "height",
        existing_type=sa.FLOAT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "offices",
        "width",
        existing_type=sa.FLOAT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "offices",
        "length",
        existing_type=sa.FLOAT(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "nodes",
        "z",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "nodes",
        "y",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "nodes",
        "x",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
