"""empty message

Revision ID: 8be6c0199de7
Revises: d4d189b0b4ec
Create Date: 2025-05-21 02:09:54.459505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8be6c0199de7"
down_revision: Union[str, None] = "d4d189b0b4ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
