"""empty message

Revision ID: 3147c686366d
Revises: 674529aea26c
Create Date: 2025-05-19 22:45:21.047270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3147c686366d"
down_revision: Union[str, None] = "674529aea26c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "role", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
