"""empty message

Revision ID: 10d5d40500b6
Revises: 0e818a7a1a55
Create Date: 2025-02-10 12:44:11.297875

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10d5d40500b6"
down_revision: Union[str, None] = "0e818a7a1a55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("is_anonymous", sa.Boolean(), nullable=False))
    op.drop_column("messages", "is_anonyumus")
    op.alter_column(
        "users",
        "password",
        type_=sa.LargeBinary(),  # BYTEA в SQLAlchemy
        postgresql_using="decode(password, 'escape')",  # Конвертация строки в байты
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "password",
        type_=sa.String(),  # Обратно в текст
        postgresql_using="encode(password, 'escape')",  # Конвертация байтов обратно в строку
    )
    op.add_column(
        "messages",
        sa.Column("is_anonyumus", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("messages", "is_anonymous")
    # ### end Alembic commands ###
