"""empty message

Revision ID: ef99d0ece217
Revises: 8be6c0199de7
Create Date: 2025-05-23 18:46:22.011101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef99d0ece217'
down_revision: Union[str, None] = '8be6c0199de7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_snapshots',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('document_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('index_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('chats', 'office_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'office_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('knowledge_snapshots')
    # ### end Alembic commands ###
