"""

Revision ID: ec7c56df1372
Revises: 98a222f9a4c0
Create Date: 2025-05-27 20:24:38.590157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec7c56df1372'
down_revision: Union[str, None] = '98a222f9a4c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('x_coord', sa.Integer(), nullable=True),
    sa.Column('y_coord', sa.Integer(), nullable=False),
    sa.Column('z_coord', sa.Integer(), nullable=False),
    sa.Column('connections', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('pid_name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('landmarks', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('deadlines', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('knowledge_snapshots', sa.Column('task_id', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('offices', sa.Column('color', sa.String(), nullable=False))
    op.add_column('offices', sa.Column('length', sa.Integer(), nullable=False))
    op.add_column('offices', sa.Column('width', sa.Integer(), nullable=False))
    op.add_column('offices', sa.Column('height', sa.Integer(), nullable=False))
    op.add_column('offices', sa.Column('floor', sa.Integer(), nullable=False))
    op.add_column('offices', sa.Column('type', sa.String(), nullable=False))
    op.add_column('offices', sa.Column('coords', sa.ARRAY(sa.FLOAT()), nullable=False))
    op.drop_column('offices', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('offices', 'coords')
    op.drop_column('offices', 'type')
    op.drop_column('offices', 'floor')
    op.drop_column('offices', 'height')
    op.drop_column('offices', 'width')
    op.drop_column('offices', 'length')
    op.drop_column('offices', 'color')
    op.drop_column('offices', 'desc')
    op.drop_column('knowledge_snapshots', 'task_id')
    op.alter_column('deadlines', 'date_from',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('nodes')
    # ### end Alembic commands ###
