"""empty message

Revision ID: cb7d3d080e37
Revises: b4e9514a6c7f
Create Date: 2025-02-22 18:41:08.341046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7d3d080e37'
down_revision: Union[str, None] = 'b4e9514a6c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('users', 'auth_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'auth_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
