"""empty message

Revision ID: 6339c2bd3f8b
Revises: 10d5d40500b6
Create Date: 2025-02-18 17:46:24.312613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6339c2bd3f8b'
down_revision: Union[str, None] = '10d5d40500b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_type')
    # ### end Alembic commands ###
