"""

Revision ID: 25d85d5b0881
Revises: f4ad34ea13fa
Create Date: 2025-05-28 15:22:45.480763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d85d5b0881'
down_revision: Union[str, None] = 'f4ad34ea13fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('thread_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('assistant_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assistant_id')
    op.drop_column('users', 'thread_id')
    # ### end Alembic commands ###
