"""

Revision ID: 01ed532f8038
Revises: e0dc8805e4a5
Create Date: 2025-05-29 18:13:25.693335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ed532f8038'
down_revision: Union[str, None] = 'e0dc8805e4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistant_messages', 'text',
               existing_type=sa.VARCHAR(length=5000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistant_messages', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###
