"""

Revision ID: fa287d25bbcd
Revises: 0a10023c25bb
Create Date: 2025-05-29 18:06:45.788860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa287d25bbcd"
down_revision: Union[str, None] = "0a10023c25bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("assistant_messages", sa.Column("type", sa.String(), nullable=False))
    op.alter_column(
        "assistant_messages",
        "text",
        existing_type=sa.VARCHAR(length=256),
        type_=sa.String(length=5000),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "assistant_messages",
        "text",
        existing_type=sa.String(length=5000),
        type_=sa.VARCHAR(length=256),
        existing_nullable=False,
    )
    op.drop_column("assistant_messages", "type")
    # ### end Alembic commands ###
