"""

Revision ID: 6b5eb6bf5b85
Revises: 1fa820fd8675
Create Date: 2025-05-30 18:28:55.059217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5eb6bf5b85'
down_revision: Union[str, None] = '1fa820fd8675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('assistant_chats_user_id_fkey', 'assistant_chats', type_='foreignkey')
    op.create_foreign_key(None, 'assistant_chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('assistant_messages_user_id_fkey', 'assistant_messages', type_='foreignkey')
    op.create_foreign_key(None, 'assistant_messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('offices_chat_id_fkey', 'offices', type_='foreignkey')
    op.drop_column('offices', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('offices_chat_id_fkey', 'offices', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'])
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'assistant_messages', type_='foreignkey')
    op.create_foreign_key('assistant_messages_user_id_fkey', 'assistant_messages', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'assistant_chats', type_='foreignkey')
    op.create_foreign_key('assistant_chats_user_id_fkey', 'assistant_chats', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
