"""empty message

Revision ID: d4d189b0b4ec
Revises: de0a205011cd
Create Date: 2025-05-20 23:52:46.131545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4d189b0b4ec'
down_revision: Union[str, None] = 'de0a205011cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
