"""

Revision ID: f4ad34ea13fa
Revises: ec7c56df1372
Create Date: 2025-05-27 20:35:06.561546

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4ad34ea13fa"
down_revision: Union[str, None] = "ec7c56df1372"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("x", sa.Integer(), nullable=True))
    op.add_column("nodes", sa.Column("y", sa.Integer(), nullable=False))
    op.add_column("nodes", sa.Column("z", sa.Integer(), nullable=False))
    op.drop_column("nodes", "x_coord")
    op.drop_column("nodes", "y_coord")
    op.drop_column("nodes", "z_coord")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nodes", sa.Column("z_coord", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "nodes", sa.Column("y_coord", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "nodes", sa.Column("x_coord", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("nodes", "z")
    op.drop_column("nodes", "y")
    op.drop_column("nodes", "x")
    # ### end Alembic commands ###
