"""

Revision ID: 1fa820fd8675
Revises: 7cc86e5abcdb
Create Date: 2025-05-29 21:05:09.097950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa820fd8675'
down_revision: Union[str, None] = '7cc86e5abcdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offices', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offices', type_='foreignkey')
    op.drop_column('offices', 'chat_id')
    # ### end Alembic commands ###
